--This is an autogenerated file built from an autogenerated file.  DO NOT MODIFY
--  Look at update_bd_wrapper.py for details
use work.types.all;
use work.AXIRegPKG.all;
use work.AXIRegPKG_d64.all;
--Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
--Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
----------------------------------------------------------------------------------
--Tool Version: Vivado v.2023.2 (lin64) Build 4029153 Fri Oct 13 20:13:54 MDT 2023
--Date        : Sat Apr 20 16:59:53 2024
--Host        : tesla.bu.edu running 64-bit AlmaLinux release 8.8 (Sapphire Caracal)
--Command     : generate_target zynq_bd_wrapper.bd
--Design      : zynq_bd_wrapper
--Purpose     : IP block netlist
----------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
library UNISIM;
use UNISIM.VCOMPONENTS.ALL;
entity zynq_bd_sane_wrapper is
  port (
    --AXI master--
    AXIM_PL_RMOSI   :  in AXIReadMOSI;
    AXIM_PL_RMISO   : out AXIReadMISO;
    AXIM_PL_WMOSI   :  in AXIWriteMOSI;
    AXIM_PL_WMISO   : out AXIWriteMISO;
    --AXI endpoint--
    CM_RMOSI        : out AXIReadMOSI;
    CM_RMISO        :  in AXIReadMISO;
    CM_WMOSI        : out AXIWriteMOSI;
    CM_WMISO        :  in AXIWriteMISO;
    --AXI endpoint--
    PLXVC_RMOSI     : out AXIReadMOSI;
    PLXVC_RMISO     :  in AXIReadMISO;
    PLXVC_WMOSI     : out AXIWriteMOSI;
    PLXVC_WMISO     :  in AXIWriteMISO;
    --AXI endpoint--
    SERV_RMOSI      : out AXIReadMOSI;
    SERV_RMISO      :  in AXIReadMISO;
    SERV_WMOSI      : out AXIWriteMOSI;
    SERV_WMISO      :  in AXIWriteMISO;
    --AXI endpoint--
    SLAVE_I2C_RMOSI : out AXIReadMOSI;
    SLAVE_I2C_RMISO :  in AXIReadMISO;
    SLAVE_I2C_WMOSI : out AXIWriteMOSI;
    SLAVE_I2C_WMISO :  in AXIWriteMISO;
    --AXI endpoint--
    SM_INFO_RMOSI   : out AXIReadMOSI;
    SM_INFO_RMISO   :  in AXIReadMISO;
    SM_INFO_WMOSI   : out AXIWriteMOSI;
    SM_INFO_WMISO   :  in AXIWriteMISO;

    C2C1B_PHY_CLK : out STD_LOGIC;
    C2C1B_PHY_DEBUG_cplllock : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_dmonitorout : out STD_LOGIC_VECTOR ( 15 downto 0 );
    C2C1B_PHY_DEBUG_eyescandataerror : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_eyescanreset : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_eyescantrigger : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_pcsrsvdin : in STD_LOGIC_VECTOR ( 15 downto 0 );
    C2C1B_PHY_DEBUG_qplllock : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_rxbufreset : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_rxbufstatus : out STD_LOGIC_VECTOR ( 2 downto 0 );
    C2C1B_PHY_DEBUG_rxcdrhold : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_rxdfelpmreset : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_rxlpmen : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_rxpcsreset : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_rxpmareset : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_rxpmaresetdone : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_rxprbscntreset : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_rxprbserr : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_rxprbssel : in STD_LOGIC_VECTOR ( 3 downto 0 );
    C2C1B_PHY_DEBUG_rxrate : in STD_LOGIC_VECTOR ( 2 downto 0 );
    C2C1B_PHY_DEBUG_rxresetdone : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_txbufstatus : out STD_LOGIC_VECTOR ( 1 downto 0 );
    C2C1B_PHY_DEBUG_txdiffctrl : in STD_LOGIC_VECTOR ( 4 downto 0 );
    C2C1B_PHY_DEBUG_txinhibit : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_txpcsreset : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_txpmareset : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_txpolarity : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_txpostcursor : in STD_LOGIC_VECTOR ( 4 downto 0 );
    C2C1B_PHY_DEBUG_txprbsforceerr : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_txprbssel : in STD_LOGIC_VECTOR ( 3 downto 0 );
    C2C1B_PHY_DEBUG_txprecursor : in STD_LOGIC_VECTOR ( 4 downto 0 );
    C2C1B_PHY_DEBUG_txresetdone : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DRP_daddr : in STD_LOGIC_VECTOR ( 9 downto 0 );
    C2C1B_PHY_DRP_den : in STD_LOGIC;
    C2C1B_PHY_DRP_di : in STD_LOGIC_VECTOR ( 15 downto 0 );
    C2C1B_PHY_DRP_do : out STD_LOGIC_VECTOR ( 15 downto 0 );
    C2C1B_PHY_DRP_drdy : out STD_LOGIC;
    C2C1B_PHY_DRP_dwe : in STD_LOGIC;
    C2C1B_PHY_Rx_rxn : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_Rx_rxp : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_Tx_txn : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_Tx_txp : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_channel_up : out STD_LOGIC;
    C2C1B_PHY_gt_pll_lock : out STD_LOGIC;
    C2C1B_PHY_hard_err : out STD_LOGIC;
    C2C1B_PHY_lane_up : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_link_reset_out : out STD_LOGIC;
    C2C1B_PHY_mmcm_not_locked_out : out STD_LOGIC;
    C2C1B_PHY_power_down : in STD_LOGIC;
    C2C1B_PHY_refclk : in STD_LOGIC;
    C2C1B_PHY_soft_err : out STD_LOGIC;
    C2C1B_aurora_do_cc : out STD_LOGIC;
    C2C1B_aurora_pma_init_in : in STD_LOGIC;
    C2C1B_aurora_reset_pb : out STD_LOGIC;
    C2C1B_axi_c2c_config_error_out : out STD_LOGIC;
    C2C1B_axi_c2c_link_error_out : out STD_LOGIC;
    C2C1B_axi_c2c_link_status_out : out STD_LOGIC;
    C2C1B_axi_c2c_multi_bit_error_out : out STD_LOGIC;
    C2C1_PHY_CLK : out STD_LOGIC;
    C2C1_PHY_DEBUG_cplllock : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_dmonitorout : out STD_LOGIC_VECTOR ( 15 downto 0 );
    C2C1_PHY_DEBUG_eyescandataerror : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_eyescanreset : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_eyescantrigger : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_pcsrsvdin : in STD_LOGIC_VECTOR ( 15 downto 0 );
    C2C1_PHY_DEBUG_qplllock : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_rxbufreset : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_rxbufstatus : out STD_LOGIC_VECTOR ( 2 downto 0 );
    C2C1_PHY_DEBUG_rxcdrhold : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_rxdfelpmreset : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_rxlpmen : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_rxpcsreset : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_rxpmareset : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_rxpmaresetdone : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_rxprbscntreset : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_rxprbserr : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_rxprbssel : in STD_LOGIC_VECTOR ( 3 downto 0 );
    C2C1_PHY_DEBUG_rxrate : in STD_LOGIC_VECTOR ( 2 downto 0 );
    C2C1_PHY_DEBUG_rxresetdone : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_txbufstatus : out STD_LOGIC_VECTOR ( 1 downto 0 );
    C2C1_PHY_DEBUG_txdiffctrl : in STD_LOGIC_VECTOR ( 4 downto 0 );
    C2C1_PHY_DEBUG_txinhibit : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_txpcsreset : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_txpmareset : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_txpolarity : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_txpostcursor : in STD_LOGIC_VECTOR ( 4 downto 0 );
    C2C1_PHY_DEBUG_txprbsforceerr : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_txprbssel : in STD_LOGIC_VECTOR ( 3 downto 0 );
    C2C1_PHY_DEBUG_txprecursor : in STD_LOGIC_VECTOR ( 4 downto 0 );
    C2C1_PHY_DEBUG_txresetdone : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DRP_daddr : in STD_LOGIC_VECTOR ( 9 downto 0 );
    C2C1_PHY_DRP_den : in STD_LOGIC;
    C2C1_PHY_DRP_di : in STD_LOGIC_VECTOR ( 15 downto 0 );
    C2C1_PHY_DRP_do : out STD_LOGIC_VECTOR ( 15 downto 0 );
    C2C1_PHY_DRP_drdy : out STD_LOGIC;
    C2C1_PHY_DRP_dwe : in STD_LOGIC;
    C2C1_PHY_Rx_rxn : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_Rx_rxp : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_Tx_txn : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_Tx_txp : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_channel_up : out STD_LOGIC;
    C2C1_PHY_gt_pll_lock : out STD_LOGIC;
    C2C1_PHY_hard_err : out STD_LOGIC;
    C2C1_PHY_lane_up : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_link_reset_out : out STD_LOGIC;
    C2C1_PHY_mmcm_not_locked_out : out STD_LOGIC;
    C2C1_PHY_power_down : in STD_LOGIC;
    C2C1_PHY_refclk : in STD_LOGIC;
    C2C1_PHY_soft_err : out STD_LOGIC;
    C2C1_aurora_do_cc : out STD_LOGIC;
    C2C1_aurora_pma_init_in : in STD_LOGIC;
    C2C1_aurora_reset_pb : out STD_LOGIC;
    C2C1_axi_c2c_config_error_out : out STD_LOGIC;
    C2C1_axi_c2c_link_error_out : out STD_LOGIC;
    C2C1_axi_c2c_link_status_out : out STD_LOGIC;
    C2C1_axi_c2c_multi_bit_error_out : out STD_LOGIC;
    C2C2B_PHY_CLK : out STD_LOGIC;
    C2C2B_PHY_DEBUG_cplllock : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_dmonitorout : out STD_LOGIC_VECTOR ( 15 downto 0 );
    C2C2B_PHY_DEBUG_eyescandataerror : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_eyescanreset : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_eyescantrigger : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_pcsrsvdin : in STD_LOGIC_VECTOR ( 15 downto 0 );
    C2C2B_PHY_DEBUG_qplllock : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_rxbufreset : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_rxbufstatus : out STD_LOGIC_VECTOR ( 2 downto 0 );
    C2C2B_PHY_DEBUG_rxcdrhold : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_rxdfelpmreset : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_rxlpmen : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_rxpcsreset : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_rxpmareset : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_rxpmaresetdone : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_rxprbscntreset : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_rxprbserr : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_rxprbssel : in STD_LOGIC_VECTOR ( 3 downto 0 );
    C2C2B_PHY_DEBUG_rxrate : in STD_LOGIC_VECTOR ( 2 downto 0 );
    C2C2B_PHY_DEBUG_rxresetdone : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_txbufstatus : out STD_LOGIC_VECTOR ( 1 downto 0 );
    C2C2B_PHY_DEBUG_txdiffctrl : in STD_LOGIC_VECTOR ( 4 downto 0 );
    C2C2B_PHY_DEBUG_txinhibit : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_txpcsreset : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_txpmareset : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_txpolarity : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_txpostcursor : in STD_LOGIC_VECTOR ( 4 downto 0 );
    C2C2B_PHY_DEBUG_txprbsforceerr : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_txprbssel : in STD_LOGIC_VECTOR ( 3 downto 0 );
    C2C2B_PHY_DEBUG_txprecursor : in STD_LOGIC_VECTOR ( 4 downto 0 );
    C2C2B_PHY_DEBUG_txresetdone : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DRP_daddr : in STD_LOGIC_VECTOR ( 9 downto 0 );
    C2C2B_PHY_DRP_den : in STD_LOGIC;
    C2C2B_PHY_DRP_di : in STD_LOGIC_VECTOR ( 15 downto 0 );
    C2C2B_PHY_DRP_do : out STD_LOGIC_VECTOR ( 15 downto 0 );
    C2C2B_PHY_DRP_drdy : out STD_LOGIC;
    C2C2B_PHY_DRP_dwe : in STD_LOGIC;
    C2C2B_PHY_Rx_rxn : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_Rx_rxp : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_Tx_txn : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_Tx_txp : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_channel_up : out STD_LOGIC;
    C2C2B_PHY_gt_pll_lock : out STD_LOGIC;
    C2C2B_PHY_hard_err : out STD_LOGIC;
    C2C2B_PHY_lane_up : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_link_reset_out : out STD_LOGIC;
    C2C2B_PHY_mmcm_not_locked_out : out STD_LOGIC;
    C2C2B_PHY_power_down : in STD_LOGIC;
    C2C2B_PHY_refclk : in STD_LOGIC;
    C2C2B_PHY_soft_err : out STD_LOGIC;
    C2C2B_aurora_do_cc : out STD_LOGIC;
    C2C2B_aurora_pma_init_in : in STD_LOGIC;
    C2C2B_aurora_reset_pb : out STD_LOGIC;
    C2C2B_axi_c2c_config_error_out : out STD_LOGIC;
    C2C2B_axi_c2c_link_error_out : out STD_LOGIC;
    C2C2B_axi_c2c_link_status_out : out STD_LOGIC;
    C2C2B_axi_c2c_multi_bit_error_out : out STD_LOGIC;
    C2C2_PHY_CLK : out STD_LOGIC;
    C2C2_PHY_DEBUG_cplllock : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_dmonitorout : out STD_LOGIC_VECTOR ( 15 downto 0 );
    C2C2_PHY_DEBUG_eyescandataerror : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_eyescanreset : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_eyescantrigger : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_pcsrsvdin : in STD_LOGIC_VECTOR ( 15 downto 0 );
    C2C2_PHY_DEBUG_qplllock : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_rxbufreset : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_rxbufstatus : out STD_LOGIC_VECTOR ( 2 downto 0 );
    C2C2_PHY_DEBUG_rxcdrhold : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_rxdfelpmreset : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_rxlpmen : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_rxpcsreset : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_rxpmareset : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_rxpmaresetdone : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_rxprbscntreset : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_rxprbserr : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_rxprbssel : in STD_LOGIC_VECTOR ( 3 downto 0 );
    C2C2_PHY_DEBUG_rxrate : in STD_LOGIC_VECTOR ( 2 downto 0 );
    C2C2_PHY_DEBUG_rxresetdone : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_txbufstatus : out STD_LOGIC_VECTOR ( 1 downto 0 );
    C2C2_PHY_DEBUG_txdiffctrl : in STD_LOGIC_VECTOR ( 4 downto 0 );
    C2C2_PHY_DEBUG_txinhibit : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_txpcsreset : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_txpmareset : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_txpolarity : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_txpostcursor : in STD_LOGIC_VECTOR ( 4 downto 0 );
    C2C2_PHY_DEBUG_txprbsforceerr : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_txprbssel : in STD_LOGIC_VECTOR ( 3 downto 0 );
    C2C2_PHY_DEBUG_txprecursor : in STD_LOGIC_VECTOR ( 4 downto 0 );
    C2C2_PHY_DEBUG_txresetdone : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DRP_daddr : in STD_LOGIC_VECTOR ( 9 downto 0 );
    C2C2_PHY_DRP_den : in STD_LOGIC;
    C2C2_PHY_DRP_di : in STD_LOGIC_VECTOR ( 15 downto 0 );
    C2C2_PHY_DRP_do : out STD_LOGIC_VECTOR ( 15 downto 0 );
    C2C2_PHY_DRP_drdy : out STD_LOGIC;
    C2C2_PHY_DRP_dwe : in STD_LOGIC;
    C2C2_PHY_Rx_rxn : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_Rx_rxp : in STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_Tx_txn : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_Tx_txp : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_channel_up : out STD_LOGIC;
    C2C2_PHY_gt_pll_lock : out STD_LOGIC;
    C2C2_PHY_hard_err : out STD_LOGIC;
    C2C2_PHY_lane_up : out STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_link_reset_out : out STD_LOGIC;
    C2C2_PHY_mmcm_not_locked_out : out STD_LOGIC;
    C2C2_PHY_power_down : in STD_LOGIC;
    C2C2_PHY_refclk : in STD_LOGIC;
    C2C2_PHY_soft_err : out STD_LOGIC;
    C2C2_aurora_do_cc : out STD_LOGIC;
    C2C2_aurora_pma_init_in : in STD_LOGIC;
    C2C2_aurora_reset_pb : out STD_LOGIC;
    C2C2_axi_c2c_config_error_out : out STD_LOGIC;
    C2C2_axi_c2c_link_error_out : out STD_LOGIC;
    C2C2_axi_c2c_link_status_out : out STD_LOGIC;
    C2C2_axi_c2c_multi_bit_error_out : out STD_LOGIC;
    CM1_PB_UART_rxd : in STD_LOGIC;
    CM1_PB_UART_txd : out STD_LOGIC;
    CM1_UART_rxd : in STD_LOGIC;
    CM1_UART_txd : out STD_LOGIC;
    CM2_PB_UART_rxd : in STD_LOGIC;
    CM2_PB_UART_txd : out STD_LOGIC;
    CM2_UART_rxd : in STD_LOGIC;
    CM2_UART_txd : out STD_LOGIC;
    ESM_UART_rxd : in STD_LOGIC;
    ESM_UART_txd : out STD_LOGIC;
    INIT_CLK : in STD_LOGIC;
    MONITOR_alarm : out STD_LOGIC;
    MONITOR_overtemp_alarm : out STD_LOGIC;
    MONITOR_vccaux_alarm : out STD_LOGIC;
    MONITOR_vccint_alarm : out STD_LOGIC;
    PL_MEM_CM_RAM_PORTB_addr : in STD_LOGIC_VECTOR ( 31 downto 0 );
    PL_MEM_CM_RAM_PORTB_clk : in STD_LOGIC;
    PL_MEM_CM_RAM_PORTB_din : in STD_LOGIC_VECTOR ( 31 downto 0 );
    PL_MEM_CM_RAM_PORTB_dout : out STD_LOGIC_VECTOR ( 31 downto 0 );
    PL_MEM_CM_RAM_PORTB_en : in STD_LOGIC;
    PL_MEM_CM_RAM_PORTB_rst : in STD_LOGIC;
    PL_MEM_CM_RAM_PORTB_we : in STD_LOGIC_VECTOR ( 3 downto 0 );
    PL_MEM_RAM_PORTB_addr : in STD_LOGIC_VECTOR ( 31 downto 0 );
    PL_MEM_RAM_PORTB_clk : in STD_LOGIC;
    PL_MEM_RAM_PORTB_din : in STD_LOGIC_VECTOR ( 31 downto 0 );
    PL_MEM_RAM_PORTB_dout : out STD_LOGIC_VECTOR ( 31 downto 0 );
    PL_MEM_RAM_PORTB_en : in STD_LOGIC;
    PL_MEM_RAM_PORTB_rst : in STD_LOGIC;
    PL_MEM_RAM_PORTB_we : in STD_LOGIC_VECTOR ( 3 downto 0 );
    SI_scl_i : in STD_LOGIC;
    SI_scl_o : out STD_LOGIC;
    SI_scl_t : out STD_LOGIC;
    SI_sda_i : in STD_LOGIC;
    SI_sda_o : out STD_LOGIC;
    SI_sda_t : out STD_LOGIC;
    SYS_RESET_bus_rst_n : out STD_LOGIC_VECTOR ( 0 to 0 );
    SYS_RESET_intcn_rst_n : out STD_LOGIC_VECTOR ( 0 to 0 );
    SYS_RESET_rst_n : out STD_LOGIC_VECTOR ( 0 to 0 );
    axi_clk : out STD_LOGIC;
    c2c_interconnect_reset : in STD_LOGIC;
    sys_resetter_c2c_bus_rst_n : out STD_LOGIC_VECTOR ( 0 to 0 );
    sys_resetter_c2c_intcn_rst_n : out STD_LOGIC_VECTOR ( 0 to 0 );
    sys_resetter_c2c_rst_n : out STD_LOGIC_VECTOR ( 0 to 0 );
    sys_resetter_primary_bus_rst_n : out STD_LOGIC_VECTOR ( 0 to 0 );
    sys_resetter_primary_intcn_rst_n : out STD_LOGIC_VECTOR ( 0 to 0 );
    sys_resetter_primary_rst_n : out STD_LOGIC_VECTOR ( 0 to 0 )
  );
end zynq_bd_sane_wrapper;

architecture STRUCTURE of zynq_bd_sane_wrapper is
  component zynq_bd is
  port (
    AXIM_PL_awaddr                           : in    STD_LOGIC_VECTOR ( 31 downto 0 );
    AXIM_PL_awprot                           : in    STD_LOGIC_VECTOR ( 2 downto 0 );
    AXIM_PL_awvalid                          : in    STD_LOGIC_VECTOR ( 0 to 0 );
    AXIM_PL_awready                          : out   STD_LOGIC_VECTOR ( 0 to 0 );
    AXIM_PL_wdata                            : in    STD_LOGIC_VECTOR ( 31 downto 0 );
    AXIM_PL_wstrb                            : in    STD_LOGIC_VECTOR ( 3 downto 0 );
    AXIM_PL_wvalid                           : in    STD_LOGIC_VECTOR ( 0 to 0 );
    AXIM_PL_wready                           : out   STD_LOGIC_VECTOR ( 0 to 0 );
    AXIM_PL_bresp                            : out   STD_LOGIC_VECTOR ( 1 downto 0 );
    AXIM_PL_bvalid                           : out   STD_LOGIC_VECTOR ( 0 to 0 );
    AXIM_PL_bready                           : in    STD_LOGIC_VECTOR ( 0 to 0 );
    AXIM_PL_araddr                           : in    STD_LOGIC_VECTOR ( 31 downto 0 );
    AXIM_PL_arprot                           : in    STD_LOGIC_VECTOR ( 2 downto 0 );
    AXIM_PL_arvalid                          : in    STD_LOGIC_VECTOR ( 0 to 0 );
    AXIM_PL_arready                          : out   STD_LOGIC_VECTOR ( 0 to 0 );
    AXIM_PL_rdata                            : out   STD_LOGIC_VECTOR ( 31 downto 0 );
    AXIM_PL_rresp                            : out   STD_LOGIC_VECTOR ( 1 downto 0 );
    AXIM_PL_rvalid                           : out   STD_LOGIC_VECTOR ( 0 to 0 );
    AXIM_PL_rready                           : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DRP_daddr                       : in    STD_LOGIC_VECTOR ( 9 downto 0 );
    C2C1_PHY_DRP_den                         : in    STD_LOGIC;
    C2C1_PHY_DRP_di                          : in    STD_LOGIC_VECTOR ( 15 downto 0 );
    C2C1_PHY_DRP_do                          : out   STD_LOGIC_VECTOR ( 15 downto 0 );
    C2C1_PHY_DRP_drdy                        : out   STD_LOGIC;
    C2C1_PHY_DRP_dwe                         : in    STD_LOGIC;
    C2C1_PHY_Rx_rxn                          : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_Rx_rxp                          : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_Tx_txn                          : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_Tx_txp                          : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_cplllock                  : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_dmonitorout               : out   STD_LOGIC_VECTOR ( 15 downto 0 );
    C2C1_PHY_DEBUG_eyescandataerror          : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_eyescanreset              : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_eyescantrigger            : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_pcsrsvdin                 : in    STD_LOGIC_VECTOR ( 15 downto 0 );
    C2C1_PHY_DEBUG_qplllock                  : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_rxbufreset                : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_rxbufstatus               : out   STD_LOGIC_VECTOR ( 2 downto 0 );
    C2C1_PHY_DEBUG_rxcdrhold                 : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_rxdfelpmreset             : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_rxlpmen                   : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_rxpcsreset                : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_rxpmareset                : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_rxpmaresetdone            : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_rxprbscntreset            : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_rxprbserr                 : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_rxprbssel                 : in    STD_LOGIC_VECTOR ( 3 downto 0 );
    C2C1_PHY_DEBUG_rxrate                    : in    STD_LOGIC_VECTOR ( 2 downto 0 );
    C2C1_PHY_DEBUG_rxresetdone               : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_txbufstatus               : out   STD_LOGIC_VECTOR ( 1 downto 0 );
    C2C1_PHY_DEBUG_txdiffctrl                : in    STD_LOGIC_VECTOR ( 4 downto 0 );
    C2C1_PHY_DEBUG_txinhibit                 : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_txpcsreset                : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_txpmareset                : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_txpolarity                : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_txpostcursor              : in    STD_LOGIC_VECTOR ( 4 downto 0 );
    C2C1_PHY_DEBUG_txprbsforceerr            : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_DEBUG_txprbssel                 : in    STD_LOGIC_VECTOR ( 3 downto 0 );
    C2C1_PHY_DEBUG_txprecursor               : in    STD_LOGIC_VECTOR ( 4 downto 0 );
    C2C1_PHY_DEBUG_txresetdone               : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DRP_daddr                      : in    STD_LOGIC_VECTOR ( 9 downto 0 );
    C2C1B_PHY_DRP_den                        : in    STD_LOGIC;
    C2C1B_PHY_DRP_di                         : in    STD_LOGIC_VECTOR ( 15 downto 0 );
    C2C1B_PHY_DRP_do                         : out   STD_LOGIC_VECTOR ( 15 downto 0 );
    C2C1B_PHY_DRP_drdy                       : out   STD_LOGIC;
    C2C1B_PHY_DRP_dwe                        : in    STD_LOGIC;
    C2C1B_PHY_Rx_rxn                         : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_Rx_rxp                         : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_Tx_txn                         : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_Tx_txp                         : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_cplllock                 : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_dmonitorout              : out   STD_LOGIC_VECTOR ( 15 downto 0 );
    C2C1B_PHY_DEBUG_eyescandataerror         : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_eyescanreset             : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_eyescantrigger           : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_pcsrsvdin                : in    STD_LOGIC_VECTOR ( 15 downto 0 );
    C2C1B_PHY_DEBUG_qplllock                 : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_rxbufreset               : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_rxbufstatus              : out   STD_LOGIC_VECTOR ( 2 downto 0 );
    C2C1B_PHY_DEBUG_rxcdrhold                : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_rxdfelpmreset            : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_rxlpmen                  : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_rxpcsreset               : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_rxpmareset               : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_rxpmaresetdone           : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_rxprbscntreset           : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_rxprbserr                : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_rxprbssel                : in    STD_LOGIC_VECTOR ( 3 downto 0 );
    C2C1B_PHY_DEBUG_rxrate                   : in    STD_LOGIC_VECTOR ( 2 downto 0 );
    C2C1B_PHY_DEBUG_rxresetdone              : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_txbufstatus              : out   STD_LOGIC_VECTOR ( 1 downto 0 );
    C2C1B_PHY_DEBUG_txdiffctrl               : in    STD_LOGIC_VECTOR ( 4 downto 0 );
    C2C1B_PHY_DEBUG_txinhibit                : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_txpcsreset               : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_txpmareset               : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_txpolarity               : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_txpostcursor             : in    STD_LOGIC_VECTOR ( 4 downto 0 );
    C2C1B_PHY_DEBUG_txprbsforceerr           : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_DEBUG_txprbssel                : in    STD_LOGIC_VECTOR ( 3 downto 0 );
    C2C1B_PHY_DEBUG_txprecursor              : in    STD_LOGIC_VECTOR ( 4 downto 0 );
    C2C1B_PHY_DEBUG_txresetdone              : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DRP_daddr                       : in    STD_LOGIC_VECTOR ( 9 downto 0 );
    C2C2_PHY_DRP_den                         : in    STD_LOGIC;
    C2C2_PHY_DRP_di                          : in    STD_LOGIC_VECTOR ( 15 downto 0 );
    C2C2_PHY_DRP_do                          : out   STD_LOGIC_VECTOR ( 15 downto 0 );
    C2C2_PHY_DRP_drdy                        : out   STD_LOGIC;
    C2C2_PHY_DRP_dwe                         : in    STD_LOGIC;
    C2C2_PHY_Rx_rxn                          : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_Rx_rxp                          : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_Tx_txn                          : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_Tx_txp                          : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_cplllock                  : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_dmonitorout               : out   STD_LOGIC_VECTOR ( 15 downto 0 );
    C2C2_PHY_DEBUG_eyescandataerror          : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_eyescanreset              : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_eyescantrigger            : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_pcsrsvdin                 : in    STD_LOGIC_VECTOR ( 15 downto 0 );
    C2C2_PHY_DEBUG_qplllock                  : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_rxbufreset                : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_rxbufstatus               : out   STD_LOGIC_VECTOR ( 2 downto 0 );
    C2C2_PHY_DEBUG_rxcdrhold                 : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_rxdfelpmreset             : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_rxlpmen                   : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_rxpcsreset                : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_rxpmareset                : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_rxpmaresetdone            : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_rxprbscntreset            : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_rxprbserr                 : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_rxprbssel                 : in    STD_LOGIC_VECTOR ( 3 downto 0 );
    C2C2_PHY_DEBUG_rxrate                    : in    STD_LOGIC_VECTOR ( 2 downto 0 );
    C2C2_PHY_DEBUG_rxresetdone               : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_txbufstatus               : out   STD_LOGIC_VECTOR ( 1 downto 0 );
    C2C2_PHY_DEBUG_txdiffctrl                : in    STD_LOGIC_VECTOR ( 4 downto 0 );
    C2C2_PHY_DEBUG_txinhibit                 : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_txpcsreset                : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_txpmareset                : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_txpolarity                : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_txpostcursor              : in    STD_LOGIC_VECTOR ( 4 downto 0 );
    C2C2_PHY_DEBUG_txprbsforceerr            : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_DEBUG_txprbssel                 : in    STD_LOGIC_VECTOR ( 3 downto 0 );
    C2C2_PHY_DEBUG_txprecursor               : in    STD_LOGIC_VECTOR ( 4 downto 0 );
    C2C2_PHY_DEBUG_txresetdone               : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DRP_daddr                      : in    STD_LOGIC_VECTOR ( 9 downto 0 );
    C2C2B_PHY_DRP_den                        : in    STD_LOGIC;
    C2C2B_PHY_DRP_di                         : in    STD_LOGIC_VECTOR ( 15 downto 0 );
    C2C2B_PHY_DRP_do                         : out   STD_LOGIC_VECTOR ( 15 downto 0 );
    C2C2B_PHY_DRP_drdy                       : out   STD_LOGIC;
    C2C2B_PHY_DRP_dwe                        : in    STD_LOGIC;
    C2C2B_PHY_Rx_rxn                         : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_Rx_rxp                         : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_Tx_txn                         : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_Tx_txp                         : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_cplllock                 : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_dmonitorout              : out   STD_LOGIC_VECTOR ( 15 downto 0 );
    C2C2B_PHY_DEBUG_eyescandataerror         : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_eyescanreset             : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_eyescantrigger           : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_pcsrsvdin                : in    STD_LOGIC_VECTOR ( 15 downto 0 );
    C2C2B_PHY_DEBUG_qplllock                 : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_rxbufreset               : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_rxbufstatus              : out   STD_LOGIC_VECTOR ( 2 downto 0 );
    C2C2B_PHY_DEBUG_rxcdrhold                : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_rxdfelpmreset            : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_rxlpmen                  : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_rxpcsreset               : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_rxpmareset               : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_rxpmaresetdone           : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_rxprbscntreset           : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_rxprbserr                : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_rxprbssel                : in    STD_LOGIC_VECTOR ( 3 downto 0 );
    C2C2B_PHY_DEBUG_rxrate                   : in    STD_LOGIC_VECTOR ( 2 downto 0 );
    C2C2B_PHY_DEBUG_rxresetdone              : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_txbufstatus              : out   STD_LOGIC_VECTOR ( 1 downto 0 );
    C2C2B_PHY_DEBUG_txdiffctrl               : in    STD_LOGIC_VECTOR ( 4 downto 0 );
    C2C2B_PHY_DEBUG_txinhibit                : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_txpcsreset               : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_txpmareset               : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_txpolarity               : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_txpostcursor             : in    STD_LOGIC_VECTOR ( 4 downto 0 );
    C2C2B_PHY_DEBUG_txprbsforceerr           : in    STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_DEBUG_txprbssel                : in    STD_LOGIC_VECTOR ( 3 downto 0 );
    C2C2B_PHY_DEBUG_txprecursor              : in    STD_LOGIC_VECTOR ( 4 downto 0 );
    C2C2B_PHY_DEBUG_txresetdone              : out   STD_LOGIC_VECTOR ( 0 to 0 );
    PL_MEM_RAM_PORTB_addr                    : in    STD_LOGIC_VECTOR ( 31 downto 0 );
    PL_MEM_RAM_PORTB_clk                     : in    STD_LOGIC;
    PL_MEM_RAM_PORTB_din                     : in    STD_LOGIC_VECTOR ( 31 downto 0 );
    PL_MEM_RAM_PORTB_dout                    : out   STD_LOGIC_VECTOR ( 31 downto 0 );
    PL_MEM_RAM_PORTB_en                      : in    STD_LOGIC;
    PL_MEM_RAM_PORTB_rst                     : in    STD_LOGIC;
    PL_MEM_RAM_PORTB_we                      : in    STD_LOGIC_VECTOR ( 3 downto 0 );
    PL_MEM_CM_RAM_PORTB_addr                 : in    STD_LOGIC_VECTOR ( 31 downto 0 );
    PL_MEM_CM_RAM_PORTB_clk                  : in    STD_LOGIC;
    PL_MEM_CM_RAM_PORTB_din                  : in    STD_LOGIC_VECTOR ( 31 downto 0 );
    PL_MEM_CM_RAM_PORTB_dout                 : out   STD_LOGIC_VECTOR ( 31 downto 0 );
    PL_MEM_CM_RAM_PORTB_en                   : in    STD_LOGIC;
    PL_MEM_CM_RAM_PORTB_rst                  : in    STD_LOGIC;
    PL_MEM_CM_RAM_PORTB_we                   : in    STD_LOGIC_VECTOR ( 3 downto 0 );
    SERV_awaddr                              : out   STD_LOGIC_VECTOR ( 31 downto 0 );
    SERV_awprot                              : out   STD_LOGIC_VECTOR ( 2 downto 0 );
    SERV_awvalid                             : out   STD_LOGIC;
    SERV_awready                             : in    STD_LOGIC;
    SERV_wdata                               : out   STD_LOGIC_VECTOR ( 31 downto 0 );
    SERV_wstrb                               : out   STD_LOGIC_VECTOR ( 3 downto 0 );
    SERV_wvalid                              : out   STD_LOGIC;
    SERV_wready                              : in    STD_LOGIC;
    SERV_bresp                               : in    STD_LOGIC_VECTOR ( 1 downto 0 );
    SERV_bvalid                              : in    STD_LOGIC;
    SERV_bready                              : out   STD_LOGIC;
    SERV_araddr                              : out   STD_LOGIC_VECTOR ( 31 downto 0 );
    SERV_arprot                              : out   STD_LOGIC_VECTOR ( 2 downto 0 );
    SERV_arvalid                             : out   STD_LOGIC;
    SERV_arready                             : in    STD_LOGIC;
    SERV_rdata                               : in    STD_LOGIC_VECTOR ( 31 downto 0 );
    SERV_rresp                               : in    STD_LOGIC_VECTOR ( 1 downto 0 );
    SERV_rvalid                              : in    STD_LOGIC;
    SERV_rready                              : out   STD_LOGIC;
    SLAVE_I2C_awaddr                         : out   STD_LOGIC_VECTOR ( 31 downto 0 );
    SLAVE_I2C_awprot                         : out   STD_LOGIC_VECTOR ( 2 downto 0 );
    SLAVE_I2C_awvalid                        : out   STD_LOGIC;
    SLAVE_I2C_awready                        : in    STD_LOGIC;
    SLAVE_I2C_wdata                          : out   STD_LOGIC_VECTOR ( 31 downto 0 );
    SLAVE_I2C_wstrb                          : out   STD_LOGIC_VECTOR ( 3 downto 0 );
    SLAVE_I2C_wvalid                         : out   STD_LOGIC;
    SLAVE_I2C_wready                         : in    STD_LOGIC;
    SLAVE_I2C_bresp                          : in    STD_LOGIC_VECTOR ( 1 downto 0 );
    SLAVE_I2C_bvalid                         : in    STD_LOGIC;
    SLAVE_I2C_bready                         : out   STD_LOGIC;
    SLAVE_I2C_araddr                         : out   STD_LOGIC_VECTOR ( 31 downto 0 );
    SLAVE_I2C_arprot                         : out   STD_LOGIC_VECTOR ( 2 downto 0 );
    SLAVE_I2C_arvalid                        : out   STD_LOGIC;
    SLAVE_I2C_arready                        : in    STD_LOGIC;
    SLAVE_I2C_rdata                          : in    STD_LOGIC_VECTOR ( 31 downto 0 );
    SLAVE_I2C_rresp                          : in    STD_LOGIC_VECTOR ( 1 downto 0 );
    SLAVE_I2C_rvalid                         : in    STD_LOGIC;
    SLAVE_I2C_rready                         : out   STD_LOGIC;
    SM_INFO_awaddr                           : out   STD_LOGIC_VECTOR ( 31 downto 0 );
    SM_INFO_awprot                           : out   STD_LOGIC_VECTOR ( 2 downto 0 );
    SM_INFO_awvalid                          : out   STD_LOGIC;
    SM_INFO_awready                          : in    STD_LOGIC;
    SM_INFO_wdata                            : out   STD_LOGIC_VECTOR ( 31 downto 0 );
    SM_INFO_wstrb                            : out   STD_LOGIC_VECTOR ( 3 downto 0 );
    SM_INFO_wvalid                           : out   STD_LOGIC;
    SM_INFO_wready                           : in    STD_LOGIC;
    SM_INFO_bresp                            : in    STD_LOGIC_VECTOR ( 1 downto 0 );
    SM_INFO_bvalid                           : in    STD_LOGIC;
    SM_INFO_bready                           : out   STD_LOGIC;
    SM_INFO_araddr                           : out   STD_LOGIC_VECTOR ( 31 downto 0 );
    SM_INFO_arprot                           : out   STD_LOGIC_VECTOR ( 2 downto 0 );
    SM_INFO_arvalid                          : out   STD_LOGIC;
    SM_INFO_arready                          : in    STD_LOGIC;
    SM_INFO_rdata                            : in    STD_LOGIC_VECTOR ( 31 downto 0 );
    SM_INFO_rresp                            : in    STD_LOGIC_VECTOR ( 1 downto 0 );
    SM_INFO_rvalid                           : in    STD_LOGIC;
    SM_INFO_rready                           : out   STD_LOGIC;
    PLXVC_awaddr                             : out   STD_LOGIC_VECTOR ( 31 downto 0 );
    PLXVC_awprot                             : out   STD_LOGIC_VECTOR ( 2 downto 0 );
    PLXVC_awvalid                            : out   STD_LOGIC;
    PLXVC_awready                            : in    STD_LOGIC;
    PLXVC_wdata                              : out   STD_LOGIC_VECTOR ( 31 downto 0 );
    PLXVC_wstrb                              : out   STD_LOGIC_VECTOR ( 3 downto 0 );
    PLXVC_wvalid                             : out   STD_LOGIC;
    PLXVC_wready                             : in    STD_LOGIC;
    PLXVC_bresp                              : in    STD_LOGIC_VECTOR ( 1 downto 0 );
    PLXVC_bvalid                             : in    STD_LOGIC;
    PLXVC_bready                             : out   STD_LOGIC;
    PLXVC_araddr                             : out   STD_LOGIC_VECTOR ( 31 downto 0 );
    PLXVC_arprot                             : out   STD_LOGIC_VECTOR ( 2 downto 0 );
    PLXVC_arvalid                            : out   STD_LOGIC;
    PLXVC_arready                            : in    STD_LOGIC;
    PLXVC_rdata                              : in    STD_LOGIC_VECTOR ( 31 downto 0 );
    PLXVC_rresp                              : in    STD_LOGIC_VECTOR ( 1 downto 0 );
    PLXVC_rvalid                             : in    STD_LOGIC;
    PLXVC_rready                             : out   STD_LOGIC;
    CM_awaddr                                : out   STD_LOGIC_VECTOR ( 31 downto 0 );
    CM_awprot                                : out   STD_LOGIC_VECTOR ( 2 downto 0 );
    CM_awvalid                               : out   STD_LOGIC;
    CM_awready                               : in    STD_LOGIC;
    CM_wdata                                 : out   STD_LOGIC_VECTOR ( 31 downto 0 );
    CM_wstrb                                 : out   STD_LOGIC_VECTOR ( 3 downto 0 );
    CM_wvalid                                : out   STD_LOGIC;
    CM_wready                                : in    STD_LOGIC;
    CM_bresp                                 : in    STD_LOGIC_VECTOR ( 1 downto 0 );
    CM_bvalid                                : in    STD_LOGIC;
    CM_bready                                : out   STD_LOGIC;
    CM_araddr                                : out   STD_LOGIC_VECTOR ( 31 downto 0 );
    CM_arprot                                : out   STD_LOGIC_VECTOR ( 2 downto 0 );
    CM_arvalid                               : out   STD_LOGIC;
    CM_arready                               : in    STD_LOGIC;
    CM_rdata                                 : in    STD_LOGIC_VECTOR ( 31 downto 0 );
    CM_rresp                                 : in    STD_LOGIC_VECTOR ( 1 downto 0 );
    CM_rvalid                                : in    STD_LOGIC;
    CM_rready                                : out   STD_LOGIC;
    CM1_UART_rxd                             : in    STD_LOGIC;
    CM1_UART_txd                             : out   STD_LOGIC;
    CM2_UART_rxd                             : in    STD_LOGIC;
    CM2_UART_txd                             : out   STD_LOGIC;
    CM1_PB_UART_rxd                          : in    STD_LOGIC;
    CM1_PB_UART_txd                          : out   STD_LOGIC;
    CM2_PB_UART_rxd                          : in    STD_LOGIC;
    CM2_PB_UART_txd                          : out   STD_LOGIC;
    ESM_UART_rxd                             : in    STD_LOGIC;
    ESM_UART_txd                             : out   STD_LOGIC;
    axi_clk                                  : out   STD_LOGIC;
    sys_resetter_primary_bus_rst_n           : out   STD_LOGIC_VECTOR ( 0 to 0 );
    sys_resetter_primary_intcn_rst_n         : out   STD_LOGIC_VECTOR ( 0 to 0 );
    sys_resetter_primary_rst_n               : out   STD_LOGIC_VECTOR ( 0 to 0 );
    c2c_interconnect_reset                   : in    STD_LOGIC;
    sys_resetter_c2c_bus_rst_n               : out   STD_LOGIC_VECTOR ( 0 to 0 );
    sys_resetter_c2c_intcn_rst_n             : out   STD_LOGIC_VECTOR ( 0 to 0 );
    sys_resetter_c2c_rst_n                   : out   STD_LOGIC_VECTOR ( 0 to 0 );
    INIT_CLK                                 : in    STD_LOGIC;
    SYS_RESET_bus_rst_n                      : out   STD_LOGIC_VECTOR ( 0 to 0 );
    SYS_RESET_intcn_rst_n                    : out   STD_LOGIC_VECTOR ( 0 to 0 );
    SYS_RESET_rst_n                          : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_aurora_pma_init_in                  : in    STD_LOGIC;
    C2C1_aurora_reset_pb                     : out   STD_LOGIC;
    C2C1_aurora_do_cc                        : out   STD_LOGIC;
    C2C1_axi_c2c_config_error_out            : out   STD_LOGIC;
    C2C1_axi_c2c_link_status_out             : out   STD_LOGIC;
    C2C1_axi_c2c_multi_bit_error_out         : out   STD_LOGIC;
    C2C1_axi_c2c_link_error_out              : out   STD_LOGIC;
    C2C1_PHY_refclk                          : in    STD_LOGIC;
    C2C1_PHY_power_down                      : in    STD_LOGIC;
    C2C1_PHY_gt_pll_lock                     : out   STD_LOGIC;
    C2C1_PHY_hard_err                        : out   STD_LOGIC;
    C2C1_PHY_soft_err                        : out   STD_LOGIC;
    C2C1_PHY_lane_up                         : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1_PHY_mmcm_not_locked_out             : out   STD_LOGIC;
    C2C1_PHY_link_reset_out                  : out   STD_LOGIC;
    C2C1_PHY_channel_up                      : out   STD_LOGIC;
    C2C1_PHY_CLK                             : out   STD_LOGIC;
    C2C1B_aurora_pma_init_in                 : in    STD_LOGIC;
    C2C1B_aurora_reset_pb                    : out   STD_LOGIC;
    C2C1B_aurora_do_cc                       : out   STD_LOGIC;
    C2C1B_axi_c2c_config_error_out           : out   STD_LOGIC;
    C2C1B_axi_c2c_link_status_out            : out   STD_LOGIC;
    C2C1B_axi_c2c_multi_bit_error_out        : out   STD_LOGIC;
    C2C1B_axi_c2c_link_error_out             : out   STD_LOGIC;
    C2C1B_PHY_refclk                         : in    STD_LOGIC;
    C2C1B_PHY_power_down                     : in    STD_LOGIC;
    C2C1B_PHY_gt_pll_lock                    : out   STD_LOGIC;
    C2C1B_PHY_hard_err                       : out   STD_LOGIC;
    C2C1B_PHY_soft_err                       : out   STD_LOGIC;
    C2C1B_PHY_lane_up                        : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C1B_PHY_mmcm_not_locked_out            : out   STD_LOGIC;
    C2C1B_PHY_link_reset_out                 : out   STD_LOGIC;
    C2C1B_PHY_channel_up                     : out   STD_LOGIC;
    C2C1B_PHY_CLK                            : out   STD_LOGIC;
    C2C2_aurora_pma_init_in                  : in    STD_LOGIC;
    C2C2_aurora_reset_pb                     : out   STD_LOGIC;
    C2C2_aurora_do_cc                        : out   STD_LOGIC;
    C2C2_axi_c2c_config_error_out            : out   STD_LOGIC;
    C2C2_axi_c2c_link_status_out             : out   STD_LOGIC;
    C2C2_axi_c2c_multi_bit_error_out         : out   STD_LOGIC;
    C2C2_axi_c2c_link_error_out              : out   STD_LOGIC;
    C2C2_PHY_refclk                          : in    STD_LOGIC;
    C2C2_PHY_power_down                      : in    STD_LOGIC;
    C2C2_PHY_gt_pll_lock                     : out   STD_LOGIC;
    C2C2_PHY_hard_err                        : out   STD_LOGIC;
    C2C2_PHY_soft_err                        : out   STD_LOGIC;
    C2C2_PHY_lane_up                         : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2_PHY_mmcm_not_locked_out             : out   STD_LOGIC;
    C2C2_PHY_link_reset_out                  : out   STD_LOGIC;
    C2C2_PHY_channel_up                      : out   STD_LOGIC;
    C2C2_PHY_CLK                             : out   STD_LOGIC;
    C2C2B_aurora_pma_init_in                 : in    STD_LOGIC;
    C2C2B_aurora_reset_pb                    : out   STD_LOGIC;
    C2C2B_aurora_do_cc                       : out   STD_LOGIC;
    C2C2B_axi_c2c_config_error_out           : out   STD_LOGIC;
    C2C2B_axi_c2c_link_status_out            : out   STD_LOGIC;
    C2C2B_axi_c2c_multi_bit_error_out        : out   STD_LOGIC;
    C2C2B_axi_c2c_link_error_out             : out   STD_LOGIC;
    C2C2B_PHY_refclk                         : in    STD_LOGIC;
    C2C2B_PHY_power_down                     : in    STD_LOGIC;
    C2C2B_PHY_gt_pll_lock                    : out   STD_LOGIC;
    C2C2B_PHY_hard_err                       : out   STD_LOGIC;
    C2C2B_PHY_soft_err                       : out   STD_LOGIC;
    C2C2B_PHY_lane_up                        : out   STD_LOGIC_VECTOR ( 0 to 0 );
    C2C2B_PHY_mmcm_not_locked_out            : out   STD_LOGIC;
    C2C2B_PHY_link_reset_out                 : out   STD_LOGIC;
    C2C2B_PHY_channel_up                     : out   STD_LOGIC;
    C2C2B_PHY_CLK                            : out   STD_LOGIC;
    MONITOR_alarm                            : out   STD_LOGIC;
    MONITOR_vccint_alarm                     : out   STD_LOGIC;
    MONITOR_vccaux_alarm                     : out   STD_LOGIC;
    MONITOR_overtemp_alarm                   : out   STD_LOGIC;
    SI_scl_i                                 : in    STD_LOGIC;
    SI_sda_i                                 : in    STD_LOGIC;
    SI_sda_o                                 : out   STD_LOGIC;
    SI_scl_o                                 : out   STD_LOGIC;
    SI_scl_t                                 : out   STD_LOGIC;
    SI_sda_t                                 : out   STD_LOGIC
  );
  end component zynq_bd;
begin
zynq_bd_i: component zynq_bd
     port map (
    AXIM_PL_araddr                           => AXIM_PL_RMOSI.address,
    AXIM_PL_arprot                           => AXIM_PL_RMOSI.protection_type,
    AXIM_PL_arready(0)                       => AXIM_PL_RMISO.ready_for_address,
    AXIM_PL_arvalid(0)                       => AXIM_PL_RMOSI.address_valid,
    AXIM_PL_awaddr                           => AXIM_PL_WMOSI.address,
    AXIM_PL_awprot                           => AXIM_PL_WMOSI.protection_type,
    AXIM_PL_awready(0)                       => AXIM_PL_WMISO.ready_for_address,
    AXIM_PL_awvalid(0)                       => AXIM_PL_WMOSI.address_valid,
    AXIM_PL_bready(0)                        => AXIM_PL_WMOSI.ready_for_response,
    AXIM_PL_bresp                            => AXIM_PL_WMISO.response,
    AXIM_PL_bvalid(0)                        => AXIM_PL_WMISO.response_valid,
    AXIM_PL_rdata                            => AXIM_PL_RMISO.data,
    AXIM_PL_rready(0)                        => AXIM_PL_RMOSI.ready_for_data,
    AXIM_PL_rresp                            => AXIM_PL_RMISO.response,
    AXIM_PL_rvalid(0)                        => AXIM_PL_RMISO.data_valid,
    AXIM_PL_wdata                            => AXIM_PL_WMOSI.data,
    AXIM_PL_wready(0)                        => AXIM_PL_WMISO.ready_for_data,
    AXIM_PL_wstrb                            => AXIM_PL_WMOSI.data_write_strobe,
    AXIM_PL_wvalid(0)                        => AXIM_PL_WMOSI.data_valid,
    C2C1B_PHY_CLK                            => C2C1B_PHY_CLK,
    C2C1B_PHY_DEBUG_cplllock                 => C2C1B_PHY_DEBUG_cplllock,
    C2C1B_PHY_DEBUG_dmonitorout              => C2C1B_PHY_DEBUG_dmonitorout,
    C2C1B_PHY_DEBUG_eyescandataerror         => C2C1B_PHY_DEBUG_eyescandataerror,
    C2C1B_PHY_DEBUG_eyescanreset             => C2C1B_PHY_DEBUG_eyescanreset,
    C2C1B_PHY_DEBUG_eyescantrigger           => C2C1B_PHY_DEBUG_eyescantrigger,
    C2C1B_PHY_DEBUG_pcsrsvdin                => C2C1B_PHY_DEBUG_pcsrsvdin,
    C2C1B_PHY_DEBUG_qplllock                 => C2C1B_PHY_DEBUG_qplllock,
    C2C1B_PHY_DEBUG_rxbufreset               => C2C1B_PHY_DEBUG_rxbufreset,
    C2C1B_PHY_DEBUG_rxbufstatus              => C2C1B_PHY_DEBUG_rxbufstatus,
    C2C1B_PHY_DEBUG_rxcdrhold                => C2C1B_PHY_DEBUG_rxcdrhold,
    C2C1B_PHY_DEBUG_rxdfelpmreset            => C2C1B_PHY_DEBUG_rxdfelpmreset,
    C2C1B_PHY_DEBUG_rxlpmen                  => C2C1B_PHY_DEBUG_rxlpmen,
    C2C1B_PHY_DEBUG_rxpcsreset               => C2C1B_PHY_DEBUG_rxpcsreset,
    C2C1B_PHY_DEBUG_rxpmareset               => C2C1B_PHY_DEBUG_rxpmareset,
    C2C1B_PHY_DEBUG_rxpmaresetdone           => C2C1B_PHY_DEBUG_rxpmaresetdone,
    C2C1B_PHY_DEBUG_rxprbscntreset           => C2C1B_PHY_DEBUG_rxprbscntreset,
    C2C1B_PHY_DEBUG_rxprbserr                => C2C1B_PHY_DEBUG_rxprbserr,
    C2C1B_PHY_DEBUG_rxprbssel                => C2C1B_PHY_DEBUG_rxprbssel,
    C2C1B_PHY_DEBUG_rxrate                   => C2C1B_PHY_DEBUG_rxrate,
    C2C1B_PHY_DEBUG_rxresetdone              => C2C1B_PHY_DEBUG_rxresetdone,
    C2C1B_PHY_DEBUG_txbufstatus              => C2C1B_PHY_DEBUG_txbufstatus,
    C2C1B_PHY_DEBUG_txdiffctrl               => C2C1B_PHY_DEBUG_txdiffctrl,
    C2C1B_PHY_DEBUG_txinhibit                => C2C1B_PHY_DEBUG_txinhibit,
    C2C1B_PHY_DEBUG_txpcsreset               => C2C1B_PHY_DEBUG_txpcsreset,
    C2C1B_PHY_DEBUG_txpmareset               => C2C1B_PHY_DEBUG_txpmareset,
    C2C1B_PHY_DEBUG_txpolarity               => C2C1B_PHY_DEBUG_txpolarity,
    C2C1B_PHY_DEBUG_txpostcursor             => C2C1B_PHY_DEBUG_txpostcursor,
    C2C1B_PHY_DEBUG_txprbsforceerr           => C2C1B_PHY_DEBUG_txprbsforceerr,
    C2C1B_PHY_DEBUG_txprbssel                => C2C1B_PHY_DEBUG_txprbssel,
    C2C1B_PHY_DEBUG_txprecursor              => C2C1B_PHY_DEBUG_txprecursor,
    C2C1B_PHY_DEBUG_txresetdone              => C2C1B_PHY_DEBUG_txresetdone,
    C2C1B_PHY_DRP_daddr                      => C2C1B_PHY_DRP_daddr,
    C2C1B_PHY_DRP_den                        => C2C1B_PHY_DRP_den,
    C2C1B_PHY_DRP_di                         => C2C1B_PHY_DRP_di,
    C2C1B_PHY_DRP_do                         => C2C1B_PHY_DRP_do,
    C2C1B_PHY_DRP_drdy                       => C2C1B_PHY_DRP_drdy,
    C2C1B_PHY_DRP_dwe                        => C2C1B_PHY_DRP_dwe,
    C2C1B_PHY_Rx_rxn                         => C2C1B_PHY_Rx_rxn,
    C2C1B_PHY_Rx_rxp                         => C2C1B_PHY_Rx_rxp,
    C2C1B_PHY_Tx_txn                         => C2C1B_PHY_Tx_txn,
    C2C1B_PHY_Tx_txp                         => C2C1B_PHY_Tx_txp,
    C2C1B_PHY_channel_up                     => C2C1B_PHY_channel_up,
    C2C1B_PHY_gt_pll_lock                    => C2C1B_PHY_gt_pll_lock,
    C2C1B_PHY_hard_err                       => C2C1B_PHY_hard_err,
    C2C1B_PHY_lane_up                        => C2C1B_PHY_lane_up,
    C2C1B_PHY_link_reset_out                 => C2C1B_PHY_link_reset_out,
    C2C1B_PHY_mmcm_not_locked_out            => C2C1B_PHY_mmcm_not_locked_out,
    C2C1B_PHY_power_down                     => C2C1B_PHY_power_down,
    C2C1B_PHY_refclk                         => C2C1B_PHY_refclk,
    C2C1B_PHY_soft_err                       => C2C1B_PHY_soft_err,
    C2C1B_aurora_do_cc                       => C2C1B_aurora_do_cc,
    C2C1B_aurora_pma_init_in                 => C2C1B_aurora_pma_init_in,
    C2C1B_aurora_reset_pb                    => C2C1B_aurora_reset_pb,
    C2C1B_axi_c2c_config_error_out           => C2C1B_axi_c2c_config_error_out,
    C2C1B_axi_c2c_link_error_out             => C2C1B_axi_c2c_link_error_out,
    C2C1B_axi_c2c_link_status_out            => C2C1B_axi_c2c_link_status_out,
    C2C1B_axi_c2c_multi_bit_error_out        => C2C1B_axi_c2c_multi_bit_error_out,
    C2C1_PHY_CLK                             => C2C1_PHY_CLK,
    C2C1_PHY_DEBUG_cplllock                  => C2C1_PHY_DEBUG_cplllock,
    C2C1_PHY_DEBUG_dmonitorout               => C2C1_PHY_DEBUG_dmonitorout,
    C2C1_PHY_DEBUG_eyescandataerror          => C2C1_PHY_DEBUG_eyescandataerror,
    C2C1_PHY_DEBUG_eyescanreset              => C2C1_PHY_DEBUG_eyescanreset,
    C2C1_PHY_DEBUG_eyescantrigger            => C2C1_PHY_DEBUG_eyescantrigger,
    C2C1_PHY_DEBUG_pcsrsvdin                 => C2C1_PHY_DEBUG_pcsrsvdin,
    C2C1_PHY_DEBUG_qplllock                  => C2C1_PHY_DEBUG_qplllock,
    C2C1_PHY_DEBUG_rxbufreset                => C2C1_PHY_DEBUG_rxbufreset,
    C2C1_PHY_DEBUG_rxbufstatus               => C2C1_PHY_DEBUG_rxbufstatus,
    C2C1_PHY_DEBUG_rxcdrhold                 => C2C1_PHY_DEBUG_rxcdrhold,
    C2C1_PHY_DEBUG_rxdfelpmreset             => C2C1_PHY_DEBUG_rxdfelpmreset,
    C2C1_PHY_DEBUG_rxlpmen                   => C2C1_PHY_DEBUG_rxlpmen,
    C2C1_PHY_DEBUG_rxpcsreset                => C2C1_PHY_DEBUG_rxpcsreset,
    C2C1_PHY_DEBUG_rxpmareset                => C2C1_PHY_DEBUG_rxpmareset,
    C2C1_PHY_DEBUG_rxpmaresetdone            => C2C1_PHY_DEBUG_rxpmaresetdone,
    C2C1_PHY_DEBUG_rxprbscntreset            => C2C1_PHY_DEBUG_rxprbscntreset,
    C2C1_PHY_DEBUG_rxprbserr                 => C2C1_PHY_DEBUG_rxprbserr,
    C2C1_PHY_DEBUG_rxprbssel                 => C2C1_PHY_DEBUG_rxprbssel,
    C2C1_PHY_DEBUG_rxrate                    => C2C1_PHY_DEBUG_rxrate,
    C2C1_PHY_DEBUG_rxresetdone               => C2C1_PHY_DEBUG_rxresetdone,
    C2C1_PHY_DEBUG_txbufstatus               => C2C1_PHY_DEBUG_txbufstatus,
    C2C1_PHY_DEBUG_txdiffctrl                => C2C1_PHY_DEBUG_txdiffctrl,
    C2C1_PHY_DEBUG_txinhibit                 => C2C1_PHY_DEBUG_txinhibit,
    C2C1_PHY_DEBUG_txpcsreset                => C2C1_PHY_DEBUG_txpcsreset,
    C2C1_PHY_DEBUG_txpmareset                => C2C1_PHY_DEBUG_txpmareset,
    C2C1_PHY_DEBUG_txpolarity                => C2C1_PHY_DEBUG_txpolarity,
    C2C1_PHY_DEBUG_txpostcursor              => C2C1_PHY_DEBUG_txpostcursor,
    C2C1_PHY_DEBUG_txprbsforceerr            => C2C1_PHY_DEBUG_txprbsforceerr,
    C2C1_PHY_DEBUG_txprbssel                 => C2C1_PHY_DEBUG_txprbssel,
    C2C1_PHY_DEBUG_txprecursor               => C2C1_PHY_DEBUG_txprecursor,
    C2C1_PHY_DEBUG_txresetdone               => C2C1_PHY_DEBUG_txresetdone,
    C2C1_PHY_DRP_daddr                       => C2C1_PHY_DRP_daddr,
    C2C1_PHY_DRP_den                         => C2C1_PHY_DRP_den,
    C2C1_PHY_DRP_di                          => C2C1_PHY_DRP_di,
    C2C1_PHY_DRP_do                          => C2C1_PHY_DRP_do,
    C2C1_PHY_DRP_drdy                        => C2C1_PHY_DRP_drdy,
    C2C1_PHY_DRP_dwe                         => C2C1_PHY_DRP_dwe,
    C2C1_PHY_Rx_rxn                          => C2C1_PHY_Rx_rxn,
    C2C1_PHY_Rx_rxp                          => C2C1_PHY_Rx_rxp,
    C2C1_PHY_Tx_txn                          => C2C1_PHY_Tx_txn,
    C2C1_PHY_Tx_txp                          => C2C1_PHY_Tx_txp,
    C2C1_PHY_channel_up                      => C2C1_PHY_channel_up,
    C2C1_PHY_gt_pll_lock                     => C2C1_PHY_gt_pll_lock,
    C2C1_PHY_hard_err                        => C2C1_PHY_hard_err,
    C2C1_PHY_lane_up                         => C2C1_PHY_lane_up,
    C2C1_PHY_link_reset_out                  => C2C1_PHY_link_reset_out,
    C2C1_PHY_mmcm_not_locked_out             => C2C1_PHY_mmcm_not_locked_out,
    C2C1_PHY_power_down                      => C2C1_PHY_power_down,
    C2C1_PHY_refclk                          => C2C1_PHY_refclk,
    C2C1_PHY_soft_err                        => C2C1_PHY_soft_err,
    C2C1_aurora_do_cc                        => C2C1_aurora_do_cc,
    C2C1_aurora_pma_init_in                  => C2C1_aurora_pma_init_in,
    C2C1_aurora_reset_pb                     => C2C1_aurora_reset_pb,
    C2C1_axi_c2c_config_error_out            => C2C1_axi_c2c_config_error_out,
    C2C1_axi_c2c_link_error_out              => C2C1_axi_c2c_link_error_out,
    C2C1_axi_c2c_link_status_out             => C2C1_axi_c2c_link_status_out,
    C2C1_axi_c2c_multi_bit_error_out         => C2C1_axi_c2c_multi_bit_error_out,
    C2C2B_PHY_CLK                            => C2C2B_PHY_CLK,
    C2C2B_PHY_DEBUG_cplllock                 => C2C2B_PHY_DEBUG_cplllock,
    C2C2B_PHY_DEBUG_dmonitorout              => C2C2B_PHY_DEBUG_dmonitorout,
    C2C2B_PHY_DEBUG_eyescandataerror         => C2C2B_PHY_DEBUG_eyescandataerror,
    C2C2B_PHY_DEBUG_eyescanreset             => C2C2B_PHY_DEBUG_eyescanreset,
    C2C2B_PHY_DEBUG_eyescantrigger           => C2C2B_PHY_DEBUG_eyescantrigger,
    C2C2B_PHY_DEBUG_pcsrsvdin                => C2C2B_PHY_DEBUG_pcsrsvdin,
    C2C2B_PHY_DEBUG_qplllock                 => C2C2B_PHY_DEBUG_qplllock,
    C2C2B_PHY_DEBUG_rxbufreset               => C2C2B_PHY_DEBUG_rxbufreset,
    C2C2B_PHY_DEBUG_rxbufstatus              => C2C2B_PHY_DEBUG_rxbufstatus,
    C2C2B_PHY_DEBUG_rxcdrhold                => C2C2B_PHY_DEBUG_rxcdrhold,
    C2C2B_PHY_DEBUG_rxdfelpmreset            => C2C2B_PHY_DEBUG_rxdfelpmreset,
    C2C2B_PHY_DEBUG_rxlpmen                  => C2C2B_PHY_DEBUG_rxlpmen,
    C2C2B_PHY_DEBUG_rxpcsreset               => C2C2B_PHY_DEBUG_rxpcsreset,
    C2C2B_PHY_DEBUG_rxpmareset               => C2C2B_PHY_DEBUG_rxpmareset,
    C2C2B_PHY_DEBUG_rxpmaresetdone           => C2C2B_PHY_DEBUG_rxpmaresetdone,
    C2C2B_PHY_DEBUG_rxprbscntreset           => C2C2B_PHY_DEBUG_rxprbscntreset,
    C2C2B_PHY_DEBUG_rxprbserr                => C2C2B_PHY_DEBUG_rxprbserr,
    C2C2B_PHY_DEBUG_rxprbssel                => C2C2B_PHY_DEBUG_rxprbssel,
    C2C2B_PHY_DEBUG_rxrate                   => C2C2B_PHY_DEBUG_rxrate,
    C2C2B_PHY_DEBUG_rxresetdone              => C2C2B_PHY_DEBUG_rxresetdone,
    C2C2B_PHY_DEBUG_txbufstatus              => C2C2B_PHY_DEBUG_txbufstatus,
    C2C2B_PHY_DEBUG_txdiffctrl               => C2C2B_PHY_DEBUG_txdiffctrl,
    C2C2B_PHY_DEBUG_txinhibit                => C2C2B_PHY_DEBUG_txinhibit,
    C2C2B_PHY_DEBUG_txpcsreset               => C2C2B_PHY_DEBUG_txpcsreset,
    C2C2B_PHY_DEBUG_txpmareset               => C2C2B_PHY_DEBUG_txpmareset,
    C2C2B_PHY_DEBUG_txpolarity               => C2C2B_PHY_DEBUG_txpolarity,
    C2C2B_PHY_DEBUG_txpostcursor             => C2C2B_PHY_DEBUG_txpostcursor,
    C2C2B_PHY_DEBUG_txprbsforceerr           => C2C2B_PHY_DEBUG_txprbsforceerr,
    C2C2B_PHY_DEBUG_txprbssel                => C2C2B_PHY_DEBUG_txprbssel,
    C2C2B_PHY_DEBUG_txprecursor              => C2C2B_PHY_DEBUG_txprecursor,
    C2C2B_PHY_DEBUG_txresetdone              => C2C2B_PHY_DEBUG_txresetdone,
    C2C2B_PHY_DRP_daddr                      => C2C2B_PHY_DRP_daddr,
    C2C2B_PHY_DRP_den                        => C2C2B_PHY_DRP_den,
    C2C2B_PHY_DRP_di                         => C2C2B_PHY_DRP_di,
    C2C2B_PHY_DRP_do                         => C2C2B_PHY_DRP_do,
    C2C2B_PHY_DRP_drdy                       => C2C2B_PHY_DRP_drdy,
    C2C2B_PHY_DRP_dwe                        => C2C2B_PHY_DRP_dwe,
    C2C2B_PHY_Rx_rxn                         => C2C2B_PHY_Rx_rxn,
    C2C2B_PHY_Rx_rxp                         => C2C2B_PHY_Rx_rxp,
    C2C2B_PHY_Tx_txn                         => C2C2B_PHY_Tx_txn,
    C2C2B_PHY_Tx_txp                         => C2C2B_PHY_Tx_txp,
    C2C2B_PHY_channel_up                     => C2C2B_PHY_channel_up,
    C2C2B_PHY_gt_pll_lock                    => C2C2B_PHY_gt_pll_lock,
    C2C2B_PHY_hard_err                       => C2C2B_PHY_hard_err,
    C2C2B_PHY_lane_up                        => C2C2B_PHY_lane_up,
    C2C2B_PHY_link_reset_out                 => C2C2B_PHY_link_reset_out,
    C2C2B_PHY_mmcm_not_locked_out            => C2C2B_PHY_mmcm_not_locked_out,
    C2C2B_PHY_power_down                     => C2C2B_PHY_power_down,
    C2C2B_PHY_refclk                         => C2C2B_PHY_refclk,
    C2C2B_PHY_soft_err                       => C2C2B_PHY_soft_err,
    C2C2B_aurora_do_cc                       => C2C2B_aurora_do_cc,
    C2C2B_aurora_pma_init_in                 => C2C2B_aurora_pma_init_in,
    C2C2B_aurora_reset_pb                    => C2C2B_aurora_reset_pb,
    C2C2B_axi_c2c_config_error_out           => C2C2B_axi_c2c_config_error_out,
    C2C2B_axi_c2c_link_error_out             => C2C2B_axi_c2c_link_error_out,
    C2C2B_axi_c2c_link_status_out            => C2C2B_axi_c2c_link_status_out,
    C2C2B_axi_c2c_multi_bit_error_out        => C2C2B_axi_c2c_multi_bit_error_out,
    C2C2_PHY_CLK                             => C2C2_PHY_CLK,
    C2C2_PHY_DEBUG_cplllock                  => C2C2_PHY_DEBUG_cplllock,
    C2C2_PHY_DEBUG_dmonitorout               => C2C2_PHY_DEBUG_dmonitorout,
    C2C2_PHY_DEBUG_eyescandataerror          => C2C2_PHY_DEBUG_eyescandataerror,
    C2C2_PHY_DEBUG_eyescanreset              => C2C2_PHY_DEBUG_eyescanreset,
    C2C2_PHY_DEBUG_eyescantrigger            => C2C2_PHY_DEBUG_eyescantrigger,
    C2C2_PHY_DEBUG_pcsrsvdin                 => C2C2_PHY_DEBUG_pcsrsvdin,
    C2C2_PHY_DEBUG_qplllock                  => C2C2_PHY_DEBUG_qplllock,
    C2C2_PHY_DEBUG_rxbufreset                => C2C2_PHY_DEBUG_rxbufreset,
    C2C2_PHY_DEBUG_rxbufstatus               => C2C2_PHY_DEBUG_rxbufstatus,
    C2C2_PHY_DEBUG_rxcdrhold                 => C2C2_PHY_DEBUG_rxcdrhold,
    C2C2_PHY_DEBUG_rxdfelpmreset             => C2C2_PHY_DEBUG_rxdfelpmreset,
    C2C2_PHY_DEBUG_rxlpmen                   => C2C2_PHY_DEBUG_rxlpmen,
    C2C2_PHY_DEBUG_rxpcsreset                => C2C2_PHY_DEBUG_rxpcsreset,
    C2C2_PHY_DEBUG_rxpmareset                => C2C2_PHY_DEBUG_rxpmareset,
    C2C2_PHY_DEBUG_rxpmaresetdone            => C2C2_PHY_DEBUG_rxpmaresetdone,
    C2C2_PHY_DEBUG_rxprbscntreset            => C2C2_PHY_DEBUG_rxprbscntreset,
    C2C2_PHY_DEBUG_rxprbserr                 => C2C2_PHY_DEBUG_rxprbserr,
    C2C2_PHY_DEBUG_rxprbssel                 => C2C2_PHY_DEBUG_rxprbssel,
    C2C2_PHY_DEBUG_rxrate                    => C2C2_PHY_DEBUG_rxrate,
    C2C2_PHY_DEBUG_rxresetdone               => C2C2_PHY_DEBUG_rxresetdone,
    C2C2_PHY_DEBUG_txbufstatus               => C2C2_PHY_DEBUG_txbufstatus,
    C2C2_PHY_DEBUG_txdiffctrl                => C2C2_PHY_DEBUG_txdiffctrl,
    C2C2_PHY_DEBUG_txinhibit                 => C2C2_PHY_DEBUG_txinhibit,
    C2C2_PHY_DEBUG_txpcsreset                => C2C2_PHY_DEBUG_txpcsreset,
    C2C2_PHY_DEBUG_txpmareset                => C2C2_PHY_DEBUG_txpmareset,
    C2C2_PHY_DEBUG_txpolarity                => C2C2_PHY_DEBUG_txpolarity,
    C2C2_PHY_DEBUG_txpostcursor              => C2C2_PHY_DEBUG_txpostcursor,
    C2C2_PHY_DEBUG_txprbsforceerr            => C2C2_PHY_DEBUG_txprbsforceerr,
    C2C2_PHY_DEBUG_txprbssel                 => C2C2_PHY_DEBUG_txprbssel,
    C2C2_PHY_DEBUG_txprecursor               => C2C2_PHY_DEBUG_txprecursor,
    C2C2_PHY_DEBUG_txresetdone               => C2C2_PHY_DEBUG_txresetdone,
    C2C2_PHY_DRP_daddr                       => C2C2_PHY_DRP_daddr,
    C2C2_PHY_DRP_den                         => C2C2_PHY_DRP_den,
    C2C2_PHY_DRP_di                          => C2C2_PHY_DRP_di,
    C2C2_PHY_DRP_do                          => C2C2_PHY_DRP_do,
    C2C2_PHY_DRP_drdy                        => C2C2_PHY_DRP_drdy,
    C2C2_PHY_DRP_dwe                         => C2C2_PHY_DRP_dwe,
    C2C2_PHY_Rx_rxn                          => C2C2_PHY_Rx_rxn,
    C2C2_PHY_Rx_rxp                          => C2C2_PHY_Rx_rxp,
    C2C2_PHY_Tx_txn                          => C2C2_PHY_Tx_txn,
    C2C2_PHY_Tx_txp                          => C2C2_PHY_Tx_txp,
    C2C2_PHY_channel_up                      => C2C2_PHY_channel_up,
    C2C2_PHY_gt_pll_lock                     => C2C2_PHY_gt_pll_lock,
    C2C2_PHY_hard_err                        => C2C2_PHY_hard_err,
    C2C2_PHY_lane_up                         => C2C2_PHY_lane_up,
    C2C2_PHY_link_reset_out                  => C2C2_PHY_link_reset_out,
    C2C2_PHY_mmcm_not_locked_out             => C2C2_PHY_mmcm_not_locked_out,
    C2C2_PHY_power_down                      => C2C2_PHY_power_down,
    C2C2_PHY_refclk                          => C2C2_PHY_refclk,
    C2C2_PHY_soft_err                        => C2C2_PHY_soft_err,
    C2C2_aurora_do_cc                        => C2C2_aurora_do_cc,
    C2C2_aurora_pma_init_in                  => C2C2_aurora_pma_init_in,
    C2C2_aurora_reset_pb                     => C2C2_aurora_reset_pb,
    C2C2_axi_c2c_config_error_out            => C2C2_axi_c2c_config_error_out,
    C2C2_axi_c2c_link_error_out              => C2C2_axi_c2c_link_error_out,
    C2C2_axi_c2c_link_status_out             => C2C2_axi_c2c_link_status_out,
    C2C2_axi_c2c_multi_bit_error_out         => C2C2_axi_c2c_multi_bit_error_out,
    CM1_PB_UART_rxd                          => CM1_PB_UART_rxd,
    CM1_PB_UART_txd                          => CM1_PB_UART_txd,
    CM1_UART_rxd                             => CM1_UART_rxd,
    CM1_UART_txd                             => CM1_UART_txd,
    CM2_PB_UART_rxd                          => CM2_PB_UART_rxd,
    CM2_PB_UART_txd                          => CM2_PB_UART_txd,
    CM2_UART_rxd                             => CM2_UART_rxd,
    CM2_UART_txd                             => CM2_UART_txd,
    CM_araddr                                => CM_RMOSI.address,
    CM_arprot                                => CM_RMOSI.protection_type,
    CM_arready                               => CM_RMISO.ready_for_address,
    CM_arvalid                               => CM_RMOSI.address_valid,
    CM_awaddr                                => CM_WMOSI.address,
    CM_awprot                                => CM_WMOSI.protection_type,
    CM_awready                               => CM_WMISO.ready_for_address,
    CM_awvalid                               => CM_WMOSI.address_valid,
    CM_bready                                => CM_WMOSI.ready_for_response,
    CM_bresp                                 => CM_WMISO.response,
    CM_bvalid                                => CM_WMISO.response_valid,
    CM_rdata                                 => CM_RMISO.data,
    CM_rready                                => CM_RMOSI.ready_for_data,
    CM_rresp                                 => CM_RMISO.response,
    CM_rvalid                                => CM_RMISO.data_valid,
    CM_wdata                                 => CM_WMOSI.data,
    CM_wready                                => CM_WMISO.ready_for_data,
    CM_wstrb                                 => CM_WMOSI.data_write_strobe,
    CM_wvalid                                => CM_WMOSI.data_valid,
    ESM_UART_rxd                             => ESM_UART_rxd,
    ESM_UART_txd                             => ESM_UART_txd,
    INIT_CLK                                 => INIT_CLK,
    MONITOR_alarm                            => MONITOR_alarm,
    MONITOR_overtemp_alarm                   => MONITOR_overtemp_alarm,
    MONITOR_vccaux_alarm                     => MONITOR_vccaux_alarm,
    MONITOR_vccint_alarm                     => MONITOR_vccint_alarm,
    PLXVC_araddr                             => PLXVC_RMOSI.address,
    PLXVC_arprot                             => PLXVC_RMOSI.protection_type,
    PLXVC_arready                            => PLXVC_RMISO.ready_for_address,
    PLXVC_arvalid                            => PLXVC_RMOSI.address_valid,
    PLXVC_awaddr                             => PLXVC_WMOSI.address,
    PLXVC_awprot                             => PLXVC_WMOSI.protection_type,
    PLXVC_awready                            => PLXVC_WMISO.ready_for_address,
    PLXVC_awvalid                            => PLXVC_WMOSI.address_valid,
    PLXVC_bready                             => PLXVC_WMOSI.ready_for_response,
    PLXVC_bresp                              => PLXVC_WMISO.response,
    PLXVC_bvalid                             => PLXVC_WMISO.response_valid,
    PLXVC_rdata                              => PLXVC_RMISO.data,
    PLXVC_rready                             => PLXVC_RMOSI.ready_for_data,
    PLXVC_rresp                              => PLXVC_RMISO.response,
    PLXVC_rvalid                             => PLXVC_RMISO.data_valid,
    PLXVC_wdata                              => PLXVC_WMOSI.data,
    PLXVC_wready                             => PLXVC_WMISO.ready_for_data,
    PLXVC_wstrb                              => PLXVC_WMOSI.data_write_strobe,
    PLXVC_wvalid                             => PLXVC_WMOSI.data_valid,
    PL_MEM_CM_RAM_PORTB_addr                 => PL_MEM_CM_RAM_PORTB_addr,
    PL_MEM_CM_RAM_PORTB_clk                  => PL_MEM_CM_RAM_PORTB_clk,
    PL_MEM_CM_RAM_PORTB_din                  => PL_MEM_CM_RAM_PORTB_din,
    PL_MEM_CM_RAM_PORTB_dout                 => PL_MEM_CM_RAM_PORTB_dout,
    PL_MEM_CM_RAM_PORTB_en                   => PL_MEM_CM_RAM_PORTB_en,
    PL_MEM_CM_RAM_PORTB_rst                  => PL_MEM_CM_RAM_PORTB_rst,
    PL_MEM_CM_RAM_PORTB_we                   => PL_MEM_CM_RAM_PORTB_we,
    PL_MEM_RAM_PORTB_addr                    => PL_MEM_RAM_PORTB_addr,
    PL_MEM_RAM_PORTB_clk                     => PL_MEM_RAM_PORTB_clk,
    PL_MEM_RAM_PORTB_din                     => PL_MEM_RAM_PORTB_din,
    PL_MEM_RAM_PORTB_dout                    => PL_MEM_RAM_PORTB_dout,
    PL_MEM_RAM_PORTB_en                      => PL_MEM_RAM_PORTB_en,
    PL_MEM_RAM_PORTB_rst                     => PL_MEM_RAM_PORTB_rst,
    PL_MEM_RAM_PORTB_we                      => PL_MEM_RAM_PORTB_we,
    SERV_araddr                              => SERV_RMOSI.address,
    SERV_arprot                              => SERV_RMOSI.protection_type,
    SERV_arready                             => SERV_RMISO.ready_for_address,
    SERV_arvalid                             => SERV_RMOSI.address_valid,
    SERV_awaddr                              => SERV_WMOSI.address,
    SERV_awprot                              => SERV_WMOSI.protection_type,
    SERV_awready                             => SERV_WMISO.ready_for_address,
    SERV_awvalid                             => SERV_WMOSI.address_valid,
    SERV_bready                              => SERV_WMOSI.ready_for_response,
    SERV_bresp                               => SERV_WMISO.response,
    SERV_bvalid                              => SERV_WMISO.response_valid,
    SERV_rdata                               => SERV_RMISO.data,
    SERV_rready                              => SERV_RMOSI.ready_for_data,
    SERV_rresp                               => SERV_RMISO.response,
    SERV_rvalid                              => SERV_RMISO.data_valid,
    SERV_wdata                               => SERV_WMOSI.data,
    SERV_wready                              => SERV_WMISO.ready_for_data,
    SERV_wstrb                               => SERV_WMOSI.data_write_strobe,
    SERV_wvalid                              => SERV_WMOSI.data_valid,
    SI_scl_i                                 => SI_scl_i,
    SI_scl_o                                 => SI_scl_o,
    SI_scl_t                                 => SI_scl_t,
    SI_sda_i                                 => SI_sda_i,
    SI_sda_o                                 => SI_sda_o,
    SI_sda_t                                 => SI_sda_t,
    SLAVE_I2C_araddr                         => SLAVE_I2C_RMOSI.address,
    SLAVE_I2C_arprot                         => SLAVE_I2C_RMOSI.protection_type,
    SLAVE_I2C_arready                        => SLAVE_I2C_RMISO.ready_for_address,
    SLAVE_I2C_arvalid                        => SLAVE_I2C_RMOSI.address_valid,
    SLAVE_I2C_awaddr                         => SLAVE_I2C_WMOSI.address,
    SLAVE_I2C_awprot                         => SLAVE_I2C_WMOSI.protection_type,
    SLAVE_I2C_awready                        => SLAVE_I2C_WMISO.ready_for_address,
    SLAVE_I2C_awvalid                        => SLAVE_I2C_WMOSI.address_valid,
    SLAVE_I2C_bready                         => SLAVE_I2C_WMOSI.ready_for_response,
    SLAVE_I2C_bresp                          => SLAVE_I2C_WMISO.response,
    SLAVE_I2C_bvalid                         => SLAVE_I2C_WMISO.response_valid,
    SLAVE_I2C_rdata                          => SLAVE_I2C_RMISO.data,
    SLAVE_I2C_rready                         => SLAVE_I2C_RMOSI.ready_for_data,
    SLAVE_I2C_rresp                          => SLAVE_I2C_RMISO.response,
    SLAVE_I2C_rvalid                         => SLAVE_I2C_RMISO.data_valid,
    SLAVE_I2C_wdata                          => SLAVE_I2C_WMOSI.data,
    SLAVE_I2C_wready                         => SLAVE_I2C_WMISO.ready_for_data,
    SLAVE_I2C_wstrb                          => SLAVE_I2C_WMOSI.data_write_strobe,
    SLAVE_I2C_wvalid                         => SLAVE_I2C_WMOSI.data_valid,
    SM_INFO_araddr                           => SM_INFO_RMOSI.address,
    SM_INFO_arprot                           => SM_INFO_RMOSI.protection_type,
    SM_INFO_arready                          => SM_INFO_RMISO.ready_for_address,
    SM_INFO_arvalid                          => SM_INFO_RMOSI.address_valid,
    SM_INFO_awaddr                           => SM_INFO_WMOSI.address,
    SM_INFO_awprot                           => SM_INFO_WMOSI.protection_type,
    SM_INFO_awready                          => SM_INFO_WMISO.ready_for_address,
    SM_INFO_awvalid                          => SM_INFO_WMOSI.address_valid,
    SM_INFO_bready                           => SM_INFO_WMOSI.ready_for_response,
    SM_INFO_bresp                            => SM_INFO_WMISO.response,
    SM_INFO_bvalid                           => SM_INFO_WMISO.response_valid,
    SM_INFO_rdata                            => SM_INFO_RMISO.data,
    SM_INFO_rready                           => SM_INFO_RMOSI.ready_for_data,
    SM_INFO_rresp                            => SM_INFO_RMISO.response,
    SM_INFO_rvalid                           => SM_INFO_RMISO.data_valid,
    SM_INFO_wdata                            => SM_INFO_WMOSI.data,
    SM_INFO_wready                           => SM_INFO_WMISO.ready_for_data,
    SM_INFO_wstrb                            => SM_INFO_WMOSI.data_write_strobe,
    SM_INFO_wvalid                           => SM_INFO_WMOSI.data_valid,
    SYS_RESET_bus_rst_n                      => SYS_RESET_bus_rst_n,
    SYS_RESET_intcn_rst_n                    => SYS_RESET_intcn_rst_n,
    SYS_RESET_rst_n                          => SYS_RESET_rst_n,
    axi_clk                                  => axi_clk,
    c2c_interconnect_reset                   => c2c_interconnect_reset,
    sys_resetter_c2c_bus_rst_n               => sys_resetter_c2c_bus_rst_n,
    sys_resetter_c2c_intcn_rst_n             => sys_resetter_c2c_intcn_rst_n,
    sys_resetter_c2c_rst_n                   => sys_resetter_c2c_rst_n,
    sys_resetter_primary_bus_rst_n           => sys_resetter_primary_bus_rst_n,
    sys_resetter_primary_intcn_rst_n         => sys_resetter_primary_intcn_rst_n,
    sys_resetter_primary_rst_n               => sys_resetter_primary_rst_n
    );
end STRUCTURE;
